### ISSUE TITLE
Adding support for Asura Scans

### ISSUE THREAD

**Issue by SharkLava** [metafates/mangal-scrapers#2]
Adding support for Asura Scans and other Madara themed sites would be nice. I'd assume that it would be similar to the Luminous Scans scraper(although I haven't been able to make it work yet). Or even a blank template of sorts for these sites would work

**Comment by metafates** [comment]
Hi! Should be similar to luminous scans, yep. I'll try to do it

**Comment by metafates** [comment]
Done! Here it is https://github.com/metafates/mangal-scrapers/blob/main/scrapers/AsuraScans.lua

**Comment by metafates** [comment]
It could be faster, but I'm too lazy to optimise it right now... 🦥

**Comment by SharkLava** [comment]
Hahaha thanks. Maybe I can try to write some for other scan groups.
