### ISSUE TITLE
cant find lua html module

### ISSUE THREAD

**Issue by sweetbbak** [metafates/mangal-scrapers#8]
I hate to open an issue for something seemingly simple like this but I cannot for the life of me find where the Lua module "html" that is used in the scrapers can be installed. I don't see it on luarocks anywhere. I wrote a few manga scrapers in python for a couple of sites and I would like to port them over to Lua but I'm still fairly new to the process of managing dependencies in Lua.

Just for clarification can you point me to where the correct html and https modules are?

**Comment by metafates** [comment]
Hi!

Mangal does not use luarocks or Lua code in general for its modules. They are written in Go and [built-int here](https://github.com/metafates/mangal-lua-libs)

Documentation isn't the best, but for the `html` module you can find it [here](https://github.com/metafates/mangal-lua-libs/tree/main/html)

**Comment by sweetbbak** [comment]
thank you, I appreciate your work and I really love mangal!
